  CREATE OR REPLACE FORCE VIEW "HIS"."HIS_STORAGE_SUMMARY" ("HIS_STORAGE_SUMMARY_ID", "AD_CLIENT_ID", "AD_ORG_ID", "CREATED", "CREATEDBY", "UPDATED", "UPDATEDBY", "HIS_STORAGE_ID", "HIS_SERVICE_ID", "VALUE", "NAME", "ENGLISHNAME", "ISHIGHTECH", "C_UOM_ID", "C_UOM_NAME", "HIS_MEASURE", "HIS_SERVICETYPE", "COUNTRYNAME", "MANUFACTURENAME", "SUPPLIERNAME", "PRICESERVICE", "PRICEASSURANCE", "PRICEDIFF", "AVAILABLEAMT", "QUANTITY", "CAPACITY", "MINVALUE", "ISLOCKED", "ISSTRICTACCESS", "ISACTIVE", "ORIGINALNAME", "CASSURANCE") AS 
  SELECT 
  MIN(SP.HIS_STORAGE_PRODUCT_ID) AS HIS_STORAGE_SUMMARY_ID,
  S.AD_CLIENT_ID, S.AD_ORG_ID, S.CREATED, S.CREATEDBY, S.UPDATED, S.UPDATEDBY,
  SP.HIS_STORAGE_ID, PI.HIS_SERVICE_ID, 
  SV.VALUE, SV.NAME, SV.ENGLISHNAME, sv.IsHighTech, SV.SECONDARY_UOM_ID C_UOM_ID,
  uom.NAME AS C_UOM_NAME, SV.HIS_MEASURE, SV.HIS_SERVICETYPE,
  country.NAME AS CountryName, man.Name AS ManufactureName, hsp.Name SupplierName ,
  MAX(PI.Price)/SV.SECONDARY_UOM_MULTIPLIER AS PriceService,
  MAX(PI.PriceAssurance)/SV.SECONDARY_UOM_MULTIPLIER AS PriceAssurance,
  MAX(PI.PriceDiff)/SV.SECONDARY_UOM_MULTIPLIER AS PriceDiff,
  SUM(SP.QUANTITY - SP.RESERVEDQUANTITY) * SV.SECONDARY_UOM_MULTIPLIER AVAILABLEAMT, SUM(SP.QUANTITY) * SV.SECONDARY_UOM_MULTIPLIER QUANTITY,
  SPM.CAPACITY, SPM.MINVALUE, SPM.ISLOCKED, SPM.IsStrictAccess,
  SV.ISACTIVE, SV.ORIGINALNAME, SV.CASSURANCE
FROM HIS_STORAGE_PRODUCT SP
  INNER JOIN HIS_PRODUCT_IMPORT PI ON SP.HIS_PRODUCT_IMPORT_ID = PI.HIS_PRODUCT_IMPORT_ID
  INNER JOIN HIS_STORAGE S ON S.HIS_STORAGE_ID = SP.HIS_STORAGE_ID
  INNER JOIN HIS_CONSUMPTION_SERVICE SV ON PI.HIS_SERVICE_ID = SV.HIS_CONSUMPTION_SERVICE_ID
  LEFT JOIN C_UOM uom ON uom.C_UOM_ID = sv.SECONDARY_UOM_ID
  LEFT JOIN HIS_STORAGE_PRODUCT_META SPM ON SPM.HIS_SERVICE_ID = PI.HIS_SERVICE_ID AND SPM.HIS_STORAGE_ID = SP.HIS_STORAGE_ID
  LEFT JOIN HIS_COUNTRY country ON SV.HIS_COUNTRY_ID = country.HIS_COUNTRY_ID
  LEFT JOIN HIS_MANUFACTURER man ON SV.HIS_MANUFACTURER_ID = man.HIS_MANUFACTURER_ID
  Left join HIS_SUPPLIER hsp on hsp.HIS_SUPPLIER_ID = sv.HIS_SUPPLIER_ID
WHERE SV.IsActive='Y'
GROUP BY 
  S.AD_CLIENT_ID, S.AD_ORG_ID, S.CREATED, S.CREATEDBY, S.UPDATED, S.UPDATEDBY,
  SP.HIS_STORAGE_ID, PI.HIS_SERVICE_ID, SV.VALUE, SV.NAME, SV.ENGLISHNAME,
  sv.IsHighTech, SV.SECONDARY_UOM_ID, uom.NAME, SV.HIS_SERVICETYPE, sv.ISACTIVE, SV.SECONDARY_UOM_MULTIPLIER,
  country.NAME, man.Name, hsp.Name, SV.ORIGINALNAME, SV.CASSURANCE,
  SPM.CAPACITY, SPM.MINVALUE, SPM.ISLOCKED, SV.HIS_MEASURE, SPM.IsStrictAccess;
  

  
  CREATE OR REPLACE FORCE VIEW "HIS"."HIS_STORAGE_SUMMARY" ("HIS_STORAGE_SUMMARY_ID", "AD_CLIENT_ID", "AD_ORG_ID", "CREATED", "CREATEDBY", "UPDATED", "UPDATEDBY", "HIS_STORAGE_ID", "HIS_SERVICE_ID", "VALUE", "NAME", "ENGLISHNAME", "ISHIGHTECH", "C_UOM_ID", "C_UOM_NAME", "HIS_MEASURE", "HIS_SERVICETYPE", "COUNTRYNAME", "MANUFACTURENAME", "SUPPLIERNAME", "PRICESERVICE", "PRICEASSURANCE", "PRICEDIFF", "AVAILABLEAMT", "QUANTITY", "CAPACITY", "MINVALUE", "ISLOCKED", "ISSTRICTACCESS", "ISACTIVE", "ORIGINALNAME", "CASSURANCE") AS 
  SELECT 
  MIN(SP.HIS_STORAGE_PRODUCT_ID) AS HIS_STORAGE_SUMMARY_ID,
  S.AD_CLIENT_ID, S.AD_ORG_ID, S.CREATED, S.CREATEDBY, S.UPDATED, S.UPDATEDBY,
  SP.HIS_STORAGE_ID, PI.HIS_SERVICE_ID, 
  SV.VALUE, SV.NAME, SV.ENGLISHNAME, sv.IsHighTech, SV.C_UOM_ID C_UOM_ID,
  uom.NAME AS C_UOM_NAME, SV.HIS_MEASURE, SV.HIS_SERVICETYPE,
  country.NAME AS CountryName, man.Name AS ManufactureName, hsp.Name SupplierName ,
  MAX(PI.Price) AS PriceService,
  MAX(PI.PriceAssurance) AS PriceAssurance,
  MAX(PI.PriceDiff) AS PriceDiff,
  SUM(SP.QUANTITY - SP.RESERVEDQUANTITY) , SUM(SP.QUANTITY) QUANTITY,
  SPM.CAPACITY, SPM.MINVALUE, SPM.ISLOCKED, SPM.IsStrictAccess,
  SV.ISACTIVE, SV.ORIGINALNAME, SV.CASSURANCE
FROM HIS_STORAGE_PRODUCT SP
  INNER JOIN HIS_PRODUCT_IMPORT PI ON SP.HIS_PRODUCT_IMPORT_ID = PI.HIS_PRODUCT_IMPORT_ID
  INNER JOIN HIS_STORAGE S ON S.HIS_STORAGE_ID = SP.HIS_STORAGE_ID
  INNER JOIN HIS_CONSUMPTION_SERVICE SV ON PI.HIS_SERVICE_ID = SV.HIS_CONSUMPTION_SERVICE_ID
  LEFT JOIN C_UOM uom ON uom.C_UOM_ID = sv.C_UOM_ID
  LEFT JOIN HIS_STORAGE_PRODUCT_META SPM ON SPM.HIS_SERVICE_ID = PI.HIS_SERVICE_ID AND SPM.HIS_STORAGE_ID = SP.HIS_STORAGE_ID
  LEFT JOIN HIS_COUNTRY country ON SV.HIS_COUNTRY_ID = country.HIS_COUNTRY_ID
  LEFT JOIN HIS_MANUFACTURER man ON SV.HIS_MANUFACTURER_ID = man.HIS_MANUFACTURER_ID
  Left join HIS_SUPPLIER hsp on hsp.HIS_SUPPLIER_ID = sv.HIS_SUPPLIER_ID
WHERE SV.IsActive='Y'
GROUP BY 
  S.AD_CLIENT_ID, S.AD_ORG_ID, S.CREATED, S.CREATEDBY, S.UPDATED, S.UPDATEDBY,
  SP.HIS_STORAGE_ID, PI.HIS_SERVICE_ID, SV.VALUE, SV.NAME, SV.ENGLISHNAME,
  sv.IsHighTech, SV.C_UOM_ID, uom.NAME, SV.HIS_SERVICETYPE, sv.ISACTIVE, SV.SECONDARY_UOM_MULTIPLIER,
  country.NAME, man.Name, hsp.Name, SV.ORIGINALNAME, SV.CASSURANCE,
  SPM.CAPACITY, SPM.MINVALUE, SPM.ISLOCKED, SV.HIS_MEASURE, SPM.IsStrictAccess;